---
:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
      fetch_data_scheduler:
        cron: '0 */14 * * *'   # Runs every 14 hours
        class: FetchDataScheduler
        queue: default
        retry: false

      article_cleanup_scheduler:
        cron:  '0 4 */2 * *'   # Runs every other night at 4 am
        class: ArticleCleanupScheduler
        queue: default
        retry: false