---
:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
      fetch_data_scheduler:
        cron: '0 */14 * * *'   # Runs every 14 hours
        class: FetchDataScheduler
        queue: default
        retry: false
